### PR TITLE
Multiple dependent jars (as URI or from database)

### PR DESCRIPTION
**Pull request by valan4ik**
Enable new parameters for the `POST /jobs` request:
      ````
      POST /jobs?cp=someURI,binName1,binName2&mainClass=some.main.Class
      ````
      `cp` accepts list of binary names (under which you uploaded binary to Jobserver) and URIs,
      `mainClass` is the main class of your application.

Main new feature of this API in comparison to using `dependent-jar-uris` is that you don't need to
specify which jar is the main one and can just send all of needed jars in one list.
Improved job and dependencies validation and error handling.

This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1267)

### CODE REVIEW

**Comment by valan4ik** [comment]
@noorul Sorry, not sure I understand. What exactly do you mean by generating TOC?
I already updated/added some documentation, if that's what you mean.

**Comment by noorul** [comment]
@valan4ik Table of contents in README is generated using DocToc. Since you added heading, you should re-generate them.

**Comment by noorul** [comment]
Also can you squash you commits into one?

**Comment by valan4ik** [comment]
@noorul Thanks for the clarification. I just checked that all headings are in TOC. For the main `README.md` I added only one new header and there is one more new documentation file (also with updated TOC).

Regarding squashing the commits, I would actually prefer not to do it as there is some logical separation between comments and squashing will produce one huge commit with 2000 modified lines. I am afraid, that it will be too huge and unclear :(

**Comment by bsikander** [comment]
@noorul are your concerns addressed?
The change looks okay to me.

**Pull request merged**
