### PR TITLE
Extension of PR #90 to support hive context...

### PR DESCRIPTION
**Pull request by nemccarthy**
This is from PR #90 from @ajmerlob to add `HiveContext` support

This seems to fix the issue of builds failing in Travis CI by adding extra memory via a `.jvmopts` file in the project's root. 

This also changes the tests to use `TestHiveContext` which handles proper cleanup of Hive metastore. 

Finally, it also fixes problems with test timeouts being to aggressive for the load time of a hive context. 

Tested in Travis CI here; https://travis-ci.org/nemccarthy/spark-jobserver/builds/56527448

(+3 squashed commits)
Squashed commits:
[fdad632] added Hive test and dummy data flatfile
[a735656] added HiveContextFactory, Hive dependencies and SparkHiveJob trait
[13e0134] added Hive support to README

### CODE REVIEW

**Comment by nightwolfzor** [comment]
+1 nice

**Comment by ajmerlob** [comment]
Wow that's awesome!

**Comment by velvia** [comment]
Thanks @nemccarthy, looking good so far.

**Comment by nightwolfzor** [comment]
Any chance this will be in 0.5.1?

**Comment by sankethd** [comment]
I have used this build to create hivecontext. Its creating hive context successfully , but creating its own metstore_db instead of the configuration I provided in spark. I have copied hive-site.xml and am able to retrieve records from spark shell, and spark submit. But when I run it through job-server , its creating its own local db as "metastore_db" in  spark-job-server/job-server folder.  Can you please help in fixing this?

**Comment by nightwolfzor** [comment]
@sankethd Are you setting the hive-site when launching the job server? Can you check the env variables?

**Comment by sankethd** [comment]
Thanks for the quick response.
No. I do not find a way to set it. May I know how  to set hive-site. ?.
(Providing an example would be more helpful)And what environment variables
you are referring here.

@sankethd <https://github.com/sankethd> Are you setting the hive-site when
launching the job server? Can you check the env variables?

—
Reply to this email directly or view it on GitHub
<https://github.com/spark-jobserver/spark-jobserver/pull/107#issuecomment-93701411>
.

**Comment by ajmerlob** [comment]
For a quick local-only workaround, consider a soft link from the job-server
folder to another local metastore_db location.  (For example, delete the
incorrect metastore_db, cd to the job-server folder and type "ln -s
/location/to/different/metastore_db" and "ln -s
/location/to/different/derby.log")

That might buy you some time.

Aaron

**Comment by sankethd** [comment]
@ajmerlob yes. Thts a good workaround for local BUT my hive metastore_db is located remotely.  As per understanding , spark job server should have to provide hive-site info while creating context or while job server launch. I do not find any way to provide this info anywhere.

**Comment by nemccarthy** [comment]
@sankethd you need to make sure hive-site.xml is on the classpath of the SJS/Spark. Put hive site on your `$SPARK_HOME\conf` as per the guide here; https://spark.apache.org/docs/latest/sql-programming-guide.html#deploying-in-existing-hive-warehouses 

    Configuration of Hive is done by placing your hive-site.xml file in conf/.

If you look at the `local.sh.template` example in SJS you will see a SPARK_HOME setting there. 
https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/config/local.sh.template#L14

Is hive-site.xml in this folder?

Please note; https://github.com/spark-jobserver/spark-jobserver/blob/master/bin/server_start.sh#L80

If you are running with `sbt reStart` then `compute_classpath.sh` is not called. You could try with the EXTRA_JAR env option (might do another PR to add an EXTRA_JARS env var which supports a csv list of jars/resources)...

**Comment by sankethd** [comment]
@nemccarthy Thanks for the response.
As I mentioned earlier, I have copied hive-site.xml in SPARK_HOME/conf. And am able to get hive results from spark shell and spark submit.
The issue is only when I submit job through job server.
And SPARK_HOME and SPARK_CONF_DIR are already set as mentioned.

I'm not sure where and how to configure this EXTRA_JAR var.

So, I have placed it in local.sh as well as in my .bashrc.
EXTRA_JAR=/home/sparkuser/softwares/spark-1.3.0-bin-hadoop2.4/conf/hive-site.xml.
And am not sure, whether I can set hive-site.xml as jar or classpath.
Still am facing the same issue.

**Comment by velvia** [comment]
@nemccarthy @ajmerlob is this PR ready to be merged?  I've looked over the code and it looks great.  Think I'm ready to push the button, and we can release 0.5.1 with this exciting feature!
Thanks so much guys.

**Comment by ajmerlob** [comment]
I've been running the code on my computer for a few weeks now, and I
haven't had any issues except the one brought up by @sankethd . This
particular issue isn't with the code from PR #90, though - it's a
configuration / devops / sysadmin issue (that I don't know how to solve).
We should probably either give the user some guidance in the readme about
how to do the configuration correctly, or add a few words to the readme
about the limitations (i.e. it always creates a brand new, embedded derby
database in the job-server folder) if we can't reliably solve the problem.

@nemccarthy <https://github.com/nemccarthy> do you actually have a remote
Hive configured and working with the job-server?  (aka you've solved the
issue @sankethd was asking about on your machine?)

Cheers,
Aaron

**Comment by velvia** [comment]
@ajmerlob @nemccarthy thanks guys. Going to merge this.

**Comment by sankethd** [comment]
Hi @nemccarthy @ajmerlob , any updates on this?

**Comment by ajmerlob** [comment]
I'm still using embedded mode, so I haven't solved this - I think
@nemccarthy is our best shot.

Aaron

**Pull request merged**
