### PR TITLE
Get latest master working with Spark 2.0

### PR DESCRIPTION
**Pull request by addisonj**
This merges latest master changes with spark-2.0-preview from @f1yegor and fixes merge conflicts.

This is confirmed to work (at least locally) with scala-2.11 builds. I am still testing for my use case (which is running under mesos).

Note, with this build, we are removing support for compiling against scala-2.10, but that seems by far the cleanest as per discussion in gitter. One possible proposal would be to make this be latest master and leave scala-2.10/spark 1.x.x as a maintenance branch

### CODE REVIEW

**Comment by noorul** [comment]
@addisonj I rebased this branch with master. Can you rebase this PR with spark-2.0-preview ?

**Comment by noorul** [comment]
@addisonj Travis is failing.

**Comment by jpgbus** [comment]
Can we exclude job-server-python module for initial PR? Or possibly include it in another branch altogether?

**Comment by velvia** [comment]
@addisonj @noorul wait what needs to happen here?   Seems can be merged right now.

**Comment by addisonj** [comment]
Tests aren't passing, as far as I know, it's only Python. I haven't had any
time to dig into what has changed with Python, but appears it may only be
dependencies.

Anyone who knows more about that, would love the input so we can get this
merged.

**Comment by velvia** [comment]
Ahh, thanks.  Lemme give it a shot, after I come back from vacay in a few days.

**Comment by bpiotr** [comment]
`SPARK_HOME` is set to 2.0.0 but you download and extract 2.0.1. This may be the reason for the error in the travis build as `PYTHONPATH` is built from it.

**Comment by addisonj** [comment]
Quick update on this.

I dug some into the python problems. It appears we are hardcoding py4j version in a few places. Since zip files on `PYTHONPATH` need to be explicit, its clear why it ended up this way, but its pretty error prone. I just changed it to the correct path for spark 2.0.1, but we really should add a utility class that searches the filesystem for all the zip files in that location.

I also had to change `HiveJobSpec` to use a `HiveContext` instead of `TestHiveContext` as in spark 2.0, `TestHiveContext` does not extend `HiveContext`, this makes it really tricky to run `HiveTestJob` without breaking the API. The test runs fine with `HiveContext` but it may leave some dropping folder behind as well as running somewhat slower.

Finally, I added a docker image to run the tests locally (basically converted travis.yml to docker) and made travis just to use that same image.

This should allow tests to be run locally much cleaner:

`docker build -f Dockerfile.test -t spark-jobserver:ci . && docker run spark-jobserver:ci`

What is left to do:

- 3 python tests are still failing with this error:
```
Error while calling 'run_job': AttributeError("'RDD' object has no attribute '_get_object_id'",)
Traceback (most recent call last):
  File "/usr/src/app/job-server-python/src/python/sparkjobserver/subprocess.py", line 107, in <module>
    result = job.run_job(context, job_env, job_data)
  File "/usr/src/app/job-server-python/src/python/example_jobs/sql_average/__init__.py", line 23, in run_job
    df = context.createDataFrame(rdd, ['name', 'age', 'salary'])
  File "/tmp/spark-2.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/context.py", line 309, in createDataFrame
    return self.sparkSession.createDataFrame(data, schema, samplingRatio, verifySchema)
  File "/tmp/spark-2.0.1-bin-hadoop2.7/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1124, in __call__
    args_command, temp_args = self._build_args(*args)
  File "/tmp/spark-2.0.1-bin-hadoop2.7/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1094, in _build_args
    [get_command_part(arg, self.pool) for arg in new_args])
  File "/tmp/spark-2.0.1-bin-hadoop2.7/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 289, in get_command_part
    command_part = REFERENCE_TYPE + parameter._get_object_id()
AttributeError: 'RDD' object has no attribute '_get_object_id'
```

This happens when trying to call `createDataFrame` with an RDD. So something has changed there...

**Comment by addisonj** [comment]
One more update...

A few more tests failures that *look* to be a race condition:
```
[info] - should survive from one job to another one *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class spark.jobserver.CommonMessages$JobResult
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass(TestKit.scala:422)
[info]   at akka.testkit.TestKit.expectMsgClass(TestKit.scala:737)
[info]   at spark.jobserver.NamedObjectsJobSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply$mcV$sp(NamedObjectsJobSpec.scala:63)
[info]   at spark.jobserver.NamedObjectsJobSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(NamedObjectsJobSpec.scala:61)
[info]   at spark.jobserver.NamedObjectsJobSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(NamedObjectsJobSpec.scala:61)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] NamedObjects (DataFrame + RDD)
[info] - should survive from one job to another one *** FAILED ***
[info]   Array("broadcast1", "df1") did not contain element "rdd1" (NamedObjectsJobSpec.scala:83)
[info] NamedObjects (Broadcast)
[info] - should survive from one job to another one *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected class spark.jobserver.CommonMessages$JobResult, found class spark.jobserver.CommonMessages$NoJobSlotsAvailable (NoJobSlotsAvailable(2))
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:436)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass(TestKit.scala:422)
[info]   at akka.testkit.TestKit.expectMsgClass(TestKit.scala:737)
[info]   at spark.jobserver.NamedObjectsJobSpec$$anonfun$4$$anonfun$apply$mcV$sp$4.apply$mcV$sp(NamedObjectsJobSpec.scala:108)
[info]   at spark.jobserver.NamedObjectsJobSpec$$anonfun$4$$anonfun$apply$mcV$sp$4.apply(NamedObjectsJobSpec.scala:98)
[info]   at spark.jobserver.NamedObjectsJobSpec$$anonfun$4$$anonfun$apply$mcV$sp$4.apply(NamedObjectsJobSpec.scala:98)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

They only fair for me when run under docker. If I run them locally, they pass just fine. I also have seen them sporadically pass in docker as well, but had increased some timeouts in various places.

With that fix, this should be clean to merge. I will see if I can spend a few minutes tomorrow, but I am kinda low on time to spend more on this.

**Comment by velvia** [comment]
@addisonj many thanks for your work on this branch.  I'm going to merge it, since it is far enough along that many people can use it, and it is a preview branch after all.

**Pull request merged**
