### PR TITLE
misc(all): Update sbt to 1.1.6 and update sbt plugins

### PR DESCRIPTION
**Pull request by LMnet**
**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [x] Docs have been added / updated (for bug fixes / features) ?

I noticed that the current version of sbt in this project was 0.13.12, which is very old. In this pull request, I updated sbt to the latest 1.1.6 version. Some additional points:
* All deprecation warnings were fixed.
* Docs was updated.
* Build scripts were updated.

Also, I updated all sbt plugins to the latest versions. Most of the updates didn't require additional work. But some did:
* `"me.lessis" % "bintray-sbt"` was renamed to `"org.foundweekends" % "sbt-bintray"`
* I completely removed `ls-sbt`, because all implicitly stuff is abandoned now. After this deletion `JobServerRelease` object has only `ourReleaseSettings` field. And I decided to rename `JobServerRelease.ourReleaseSettings` to `Release.settings` because it's less verbose and more clear IMO.
* I added `skip in publish := true` setting in the `noPublishSettings`. This is a recommended way to skip publishing now.

I think some extra improvements could be done with the sbt code after this updates, but I decided to make this pull request as small as possible.

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1099)

### CODE REVIEW

**Comment by bsikander** [comment]
Overall +1. It works. I just found the following warnings,

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* io.netty:netty-all:4.0.44.Final is selected over 4.0.33.Final
[warn] 	    +- spark.jobserver:job-server-api_2.11:0.8.1-SNAPSHOT (depends on 4.0.33.Final)
[warn] 	    +- spark.jobserver:akka-app_2.11:0.8.1-SNAPSHOT       (depends on 4.0.33.Final)
[warn] 	    +- spark.jobserver:job-server_2.11:0.8.1-SNAPSHOT     (depends on 4.0.33.Final)
[warn] 	    +- com.datastax.spark:spark-cassandra-connector_2.11:2.0.5 (depends on 4.0.33.Final)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating job-server-extras...
```

**Comment by bsikander** [comment]
btw what is your opinion on using zinc?

**Comment by bsikander** [comment]
@velvia @noorul could you also have a look at this?

**Comment by bsikander** [comment]
Oh, it seems that zinc is already part of new sbt 1.0.0.

**Comment by LMnet** [comment]
@bsikander about warnings - it's dependencies warnings, not sbt itself. Looks like old sbt didn't show these warnings or just can't understand this type of issues.

Also, there is sbt 1.2.0 already released. I could update this pull request, this release should not affect my changes.

**Comment by bsikander** [comment]
I was on vacations, so couldn't respond.

sbt 1.2.0 is quite new and already has a minor version. I think for some time we should stick to 1.1.6.
If you are okay with this, then I will go ahead and merge this change.

**Comment by bsikander** [comment]
Thanks you for the change.

**Pull request merged**
