### PR TITLE
Crossbuilding for 2.10 and 2.11

### PR DESCRIPTION
**Pull request by zeitos**

### CODE REVIEW

**Comment by velvia** [comment]
@zeitos thanks. Would you mind adding something to README to let others know how to build with 2.11?  (`+publish`, or `++2.11.6` followed by regular commands?)

**Comment by velvia** [comment]
Otherwise :+1:

**Comment by zeitos** [comment]
and the deploy script!

**Comment by zeitos** [comment]
One thing I just noticed, I forgot to add travis config for 2.11! :ghost:

**Comment by zeitos** [comment]
build is failing for 2.11 b/c of a timeout, it's passing on my local machine so I'm increasing the timeout

**Comment by zeitos** [comment]
@velvia  Can you re-review?

**Comment by velvia** [comment]
Sure, will probably look tonight

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Meadow

**Pull request merged**
