### PR TITLE
Add code coverage to .travis.yml

### PR DESCRIPTION
**Pull request by hntd187**
Add some code coverage

### CODE REVIEW

**Comment by velvia** [comment]
👍 
Maybe these three changes can be squashed down?

**Comment by hntd187** [comment]
I believe I can sqash it down to one commit when it gets merged.

**Comment by noorul** [comment]
I think we should remove job-server-tests folder from this

**Comment by zeitos** [comment]
Nice! 🌟🌟🌟🌟🌟

**Comment by hntd187** [comment]
@noorul why? They are code that is used by people to verify the server and we should verify they work as intended.

**Comment by noorul** [comment]
Agree that whatever code we write should have test cases. But we do not have them in job-server-tests. Why to run coverage on folder in which we have no tests?

**Comment by hntd187** [comment]
@noorul I am also suggesting we write tests for them. 😄 Since they are integration tests they should have unit tests covering them to ensure they don't regress in a new release and can be a reliable verification of the entire system.

**Comment by noorul** [comment]
Agreed!

**Pull request merged**
