### PR TITLE
Upgrade sbt and sbt plugins: sbt-revolver, sbt-assembly, and sbt-docker

### PR DESCRIPTION
**Pull request by jaceklaskowski**
The title says it all. Please review @velvia and merge at your convenience. Thanks.

### CODE REVIEW

**Comment by hntd187** [comment]
Fantastic, saves me the time doing this. Were the other plugins already up to date?

**Comment by jaceklaskowski** [comment]
No other plugins upgraded. I think one or two might be begging for upgrade, but when I tried to upgrade them I had issues I couldn't solve. That's why I was so specific about the plugins in the pr.

**Comment by velvia** [comment]
@jaceklaskowski many thanks!  Say would you mind merging master, I merged @hntd187 's changes, probably very minor conflicts.

**Comment by jaceklaskowski** [comment]
@velvia Please review. Thanks!

**Comment by jaceklaskowski** [comment]
@velvia mind reviewing and merging the change? It works for me locally.

```
➜  spark-jobserver git:(sbt-plugins-update) sbt ++2.10.6 test
...
[info] Tests: succeeded 18, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 135 s, completed Apr 22, 2016 1:37:28 PM
```

**Comment by hntd187** [comment]
@jaceklaskowski this pull request is prolly already taken care of by #435 but also some of the tests are flakey, so it's just a matter sometimes of running them again. But you gotta give @velvia a few days, he's a pretty busy guy

**Comment by velvia** [comment]
@jaceklaskowski thx, going to merge

**Pull request merged**
