### PR TITLE
Rename SslContextFactory as SSLContextFactory

### PR DESCRIPTION
**Pull request by noorul**

### CODE REVIEW

**Comment by TimMaltGermany** [comment]
Thanks.

**Comment by noorul** [comment]
No problems

**Comment by TimMaltGermany** [comment]
I just noticed a minor glitch. I log the keystore type instead of the encryption type in line 35. Could you please change that as well?
replace:
logger.info(keystoreType + " encryption activated.")
with:
logger.info(config.getString("encryptionType") + " encryption activated.")
(or create a local variable if you prefer)

Thanks, Tim

**Comment by noorul** [comment]
Done!

**Comment by velvia** [comment]
@noorul thanks!

**Pull request merged**
