### PR TITLE
feat(pythonJob): Support HDFS pyFiles dependencies in cluster

### PR DESCRIPTION
**Pull request by gao634209276**
On the cluster side, PythonJob dependencies need to be installed
into the python instance to be used for running the jobs,
or added to the list of paths in config, This change supports
pythonJob HDFS type dependencies use config:
spark.context-settings.launcher.py-files.

**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1174)

### CODE REVIEW

**Comment by gao634209276** [comment]
It works on YARN mode, I have not tested on  Mesos/Standalone mode. Due to the use of `spark.submit.pyFiles`, it may also take effect. Can anyone test it?

**Comment by noorul** [comment]
Can you rebase?

**Comment by bsikander** [comment]
Testcases need to be added for ManagerLauncher. Almost all tests are failing for this class.

**Comment by gao634209276** [comment]
Is this ok now?

**Comment by bsikander** [comment]
@gao634209276 please rebase your change on current master so tests can be executed.

**Pull request closed without merging**
