### PR TITLE
Support user impersonation for an already Kerberos authenticated user

### PR DESCRIPTION
**Pull request by mateilucianstefan**
Extract OPTIONAL parameter spark.proxy.user from contextConfig and pa…

### CODE REVIEW

**Comment by velvia** [comment]
@mateilucianstefan thanks, LGTM.  Would you mind adding a note in the README somewhere?

**Comment by mateilucianstefan** [comment]
Adding it to the [Context configuration](https://github.com/spark-jobserver/spark-jobserver#context-configuration) section seems be a good choice. What do you think @velvia ?

**Comment by velvia** [comment]
Sounds good, thanks!

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by mateilucianstefan** [comment]
Some tests are failing, but cannot be because of the readme file update :)

**Comment by velvia** [comment]
Yeah it's ok. There is a flaky test.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
@mateilucianstefan thanks! merging.

**Pull request merged**
