### PR TITLE
Improving error handling 

### PR DESCRIPTION
**Pull request by zeitos**
Logs errors when an exception occur while launching a new job.
Adds a nice message to users in case they try to use the current code with a jar compiled for a previous version.

### CODE REVIEW

**Comment by velvia** [comment]
@zeitos thanks.

**Comment by jomach** [comment]
Hi Guys, So I'm getting this error.  Can someone explain this previous version a litte better. I have  on my maven file :        

       <dependency>
            <groupId>spark.jobserver</groupId>
            <artifactId>job-server-api_2.10</artifactId>
            <version>0.6.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>spark.jobserver</groupId>
            <artifactId>job-server-extras_2.10</artifactId>
            <version>0.6.2</version>
            <scope>provided</scope>

I do : mvn clean compile assembly:single

curl ... create sql-context
curl ... upload jar

execute the job : curl -d "" '127.0.0.1:8090/jobs?appName=testapp&classPath=myclas&context=sql-context&sync=true'

[2016-07-18 09:56:59,440] ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/sql-context] - Oops, there's an AbstractMethodError... maybe you compiled your code with an older version of SJS? here's the exception:
java.lang.AbstractMethodError
	at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:278)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hntd187** [comment]
@jomach Open an issue for this, let's keep this regarding the pull request.

**Comment by v-gerasimov** [comment]
I don't agree with this improving and it would be perfect to revert this PR. Threre are some reasons:

- Most people use Logstash or something else to get logs of their applications and send message to their email if something is wrong. Usually if I have message with `Error` level it means that something really bad has happend. With this improvements I get message with `Error` level twice with the same exception for example: I want to stop my job by spark-jobserver API and get two errors: first error is 

    ```ERROR spark.jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/spark-tools] - Got Throwable
org.apache.spark.SparkException: Job 361 cancelled part of cancelled job group fb6359e9-2c5d-463e-be4c-3d3b75623b03```

 and the second is 

    ```ERROR spark.jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/spark-tools] - Exception from job fb6359e9-2c5d-463e-be4c-3d3b75623b03: 
org.apache.spark.SparkException: Job 361 cancelled part of cancelled job group fb6359e9-2c5d-463e-be4c-3d3b75623b03```.

    However I think it is wrong when user stops job by API and you get error log (especially twice). Another example when user does something wrong: user try to run sql query like "nothing else matters"  and you get the next messages: 

    ```ERROR spark.jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/spark-tools] - Got Throwable
java.lang.RuntimeException: Sql parsing exception: [1.1] failure: ``with'' expected but identifier nothing found```

    and 

    ```ERROR spark.jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/spark-tools] - Exception from job c0866933-3f99-4c88-81d2-8a81a7f9c3c6: 
java.lang.RuntimeException: Sql parsing exception: [1.1] failure: ``with'' expected but identifier nothing found```. 

    Why? User can see this error in job result:

    ```
{
  "duration": "0.269 secs",
  "classPath": "com.mycompany.Job",
  "startTime": "2016-09-15T15:35:28.880+06:00",
  "context": "test-context",
  "result": {
    "message": "java.lang.RuntimeException: [1.1] failure: ``with'' expected but identifier nothing found\n\nnothing else matters\n^",
    "errorClass": "java.lang.Throwable",
    "stack": ["spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfo$1$$anonfun$apply$12$$anonfun$apply$14.apply(JobSqlDAO.scala:303)", "spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfo$1$$anonfun$apply$12$$anonfun$apply$14.apply(JobSqlDAO.scala:303)", "scala.Option.map(Option.scala:146)", "spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfo$1$$anonfun$apply$12.apply(JobSqlDAO.scala:303)", "spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfo$1$$anonfun$apply$12.apply(JobSqlDAO.scala:296)", "scala.collection.immutable.List.map(List.scala:273)", "spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfo$1.apply(JobSqlDAO.scala:296)", "spark.jobserver.io.JobSqlDAO$$anonfun$getJobInfo$1.apply(JobSqlDAO.scala:287)", "scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)", "scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)", "spark.jobserver.io.JobSqlDAO.getJobInfo(JobSqlDAO.scala:286)", "spark.jobserver.JobInfoActor$$anonfun$wrappedReceive$1.applyOrElse(JobInfoActor.scala:38)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:467)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"]
  },
  "status": "ERROR",
  "jobId": "c0866933-3f99-4c88-81d2-8a81a7f9c3c6"
}
```
, so why we should get error logs in this case?

- What happens if my job can throw `java.lang.AbstractMethodError` in `runJob` method? For example:
    ```scala
object Test extends SparkSqlJob {
  override def runJob(sc: SQLContext, config: Config) = {
    throw new AbstractMethodError()
  }

  override def validate(sc: SQLContext, config: Config) = SparkJobValid
}
```
You get the next error: `ERROR spark.jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/test] - Oops, there's an AbstractMethodError... maybe you compiled your code with an older version of SJS? here's the exception:
java.lang.AbstractMethodError`. I think this message can trouble user.

Any improvements in logging is certainly beautiful, but I think we should keep spark-jobserver errors separate user job errors. And if something wrong is happening in spark-jobserver it should have `Error` level log, another errors should have `Warn` level.

**Comment by zeitos** [comment]
@v-gerasimov the important part in this PR is the AbstractMethodError message which was (is) hard to find to many users (as you can see: even with that explanation)

About the double logging: I agree, it's wrong, and we should change that.

About the java.lang.AbstractMethodError: you have the exception, the message is just a tip for a common error that users get, the exception comes with a tip of what it *might* be but the de developer should always look at the exception. Differentiating user and SJS errors in this particular case might not be that easy to solve, and I'm not sure it's worth the trouble.

**Pull request merged**
