### PR TITLE
Spark3.0.1

### PR DESCRIPTION
**Pull request by dberardo-com**
**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1353)

### CODE REVIEW

**Comment by dberardo-com** [comment]
the pipeline is failing because of docker hub pull limitations ...

**Comment by valan4ik** [comment]
Hi @dberardo-com ,

The tests are failing:
```
ERROR: test_run_sql_job (__main__.TestSJSApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/apitests.py", line 118, in test_run_sql_job
    sqlContext = SQLContext(self.sc)
  File "/tmp/spark-3.0.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/context.py", line 83, in __init__
    sparkSession = SparkSession.builder.getOrCreate()
  File "/tmp/spark-3.0.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/session.py", line 189, in getOrCreate
    session = SparkSession(sc)
  File "/tmp/spark-3.0.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in __init__
    jsparkSession = self._jvm.SparkSession(self._jsc.sc())
AttributeError: 'NoneType' object has no attribute 'sc'
```

If you would like to make it possible to use Spark 3.0, then you need to upgrade jobserver [dependencies](https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Versions.scala#L4). I suspect that this change requires a lot of testing and some additional code changes.

**Comment by dberardo-com** [comment]
well @valan4ik i am really not a scala developer, so i can give it a quick try, but i will be reaching my limit after the first attempt :D 

i have reported the errors in the tests yesteday in this issue https://github.com/spark-jobserver/spark-jobserver/issues/1269

the pipeline is failing because of another reason, but sure the tests will eventually fail.

Also i have now a completely different issue: i have tried to start the container using the app/start_server.sh script, and it seems that log4j properties file and .jars are missing ... this is very strange, i would expect the server to startup and eventually maybe crash, when SparkSQL is intended to run, but not starting at all because jars are not found .... what am i doing wrong here (P.S. i am using the same exact image as Dockerfile.test, but removed the CMD and added ENTRYPOINT /usr/..../app/start_server.sh)

**Comment by valan4ik** [comment]
Hi @dberardo-com ,

Pipeline failed first due to docker pull problem, but I restarted it got test error above. This is exactly the same test error as you posted in the issue. 
Currently you changed only version of Spark for the test setup, but versions should be still updated for Jobserver project itself, e.g. [Spark version](https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Versions.scala#L4), [Hadoop version](https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Versions.scala#L13), [Cassandra connector version](https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Versions.scala#L33) (it's just a few I could remember right away, I am not sure right now what else can be needed).

**Comment by dberardo-com** [comment]
@valan4ik i can probably get back to this next week. But i look forward for some support, as i really cannot guarantee on my results with scala.

Also, i understood how to run tests, but is still dont understand how is the job-server supposed to start .... i think docu is missing here.

**Comment by Ennosigaeon** [comment]
@dberardo-com I had also planed to provide a PR to upgrade to spark 3 but had no time to start yet. Just let me know if you need help with the Scala part, I can give it a try.

@valan4ik How is the plan on supporting Spark 2 for > 0.11.0 versions? Is it ok to drop support for spark 2?

**Comment by valan4ik** [comment]
Hi @Ennosigaeon ,
I think we shouldn't drop Spark 2 support right away. I think it would make sense to make one more (1.x) release with Spark 2.4 and only then switch completely to Spark 3 and Scala 2.12.
Not sure how different Spark 3 is and how many changes does it bring with it.

**Comment by Ennosigaeon** [comment]
@dberardo-com I have created my own PR for Spark 3 support (see #1359). Feel free to give it a try to check if everything is working as expected.

**Comment by valan4ik** [comment]
As https://github.com/spark-jobserver/spark-jobserver/pull/1359 was opened and this PR seems to be incomplete and inactive now, I will close it.

**Pull request closed without merging**
