### PR TITLE
remove streams when the context is stopped - ref spark-jobserver#1119

### PR DESCRIPTION
**Pull request by archetana**
**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [x] Tests for the changes have been added (for bug fixes / features) ?
- [x] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1125)

### CODE REVIEW

**Comment by bsikander** [comment]
Reopened the PR to retrigger the testcases.
+1 for cleanup.

**Comment by bsikander** [comment]
Please change your commit message according the [contribution guidelines](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/contribution-guidelines.md).

**Comment by bsikander** [comment]
Ping @archetana

**Comment by archetana** [comment]
@bsikander - modified the commit message

**Comment by bsikander** [comment]
Retriggering the testcases

**Comment by bsikander** [comment]
umm strange, the testcases failing during the initial tests. Retriggering.

**Comment by bsikander** [comment]
1 unrelated test failed. Merging.
Thanks.

**Pull request merged**
