### PR TITLE
Add jvmopts to increase default travis-ci memory and support hive contex...

### PR DESCRIPTION
**Pull request by nemccarthy**
This is from PR #90 from @ajmerlob 

This seems to fix the issue of builds failing in Travis CI by adding extra memory via a `.jvmopts` file in the project's root. 

(+3 squashed commits)
Squashed commits:
[fdad632] added Hive test and dummy data flatfile
[a735656] added HiveContextFactory, Hive dependencies and SparkHiveJob trait
[13e0134] added Hive support to README

### CODE REVIEW

**Comment by nemccarthy** [comment]
Jenkins please retest

**Comment by ajmerlob** [comment]
Hey, so how do I do this?

**Comment by ajmerlob** [comment]
Hmm... that seemed promising

**Comment by ajmerlob** [comment]
@nemccarthy BTW, did the Hive code work for you on your box?  I wonder if maybe a solution is to ship a stripped down derby database + metastore_db so that travis-ci doesn't have to actually create a new one (which may be the step that foils it - who knows).

**Comment by nemccarthy** [comment]
Back to the drawing board haha... @ajmerlob going to test here first; https://travis-ci.org/nemccarthy/spark-jobserver/ if you have any ideas we can test there before trying 100 changes in the pr here

**Comment by ajmerlob** [comment]
Teamwork!!

**Comment by nemccarthy** [comment]
FTW! 

I also fixed up that failing `"can add contexts from jobConfig"` test

**Comment by ajmerlob** [comment]
Wow, that's awesome about jobConfig. Did you try adding the derby + metastore_db to the commit?  I can't figure out how to send in a PR to your travis-ci thing.

**Comment by nemccarthy** [comment]
Ok, so I see whats wrong. When writing Spark Hive tests, generally I use `TestHive` which creates a `TestHiveContext` which solves the problems with paths... This is a problem because the ContextFactory for Hive is creating a new HiveContext when really we want it to create a new TestHiveContext...

**Comment by velvia** [comment]
@ajmerlob @nemccarthy this looks great.  Do you want to reopen it and try again?   If you push a dummy commit then Travis should rebuild.   We definitely want to get more memory for the builds if possible!

**Comment by nemccarthy** [comment]
Thanks @velvia Re-opened #107 Would be great to get feedback. FYI http://docs.travis-ci.com/user/ci-environment/ Travis build node has 3GB of RAM.

**Pull request closed without merging**
