### PR TITLE
Mesos config tips

### PR DESCRIPTION
**Pull request by vatsalmevada**
With reference to issue #812, adding mesos mode configuration steps. The steps mentioned in the configuration worked for me.

@LeightonWong you might also want to review the steps once.

### CODE REVIEW

**Comment by vatsalmevada** [comment]
@velvia I have committed the change on spark-2.0-preview since I have done all the testing on spark 2.0.2 version. However, as @LeightonWong have already tried the same config with spark 1.6 I think it should work with spark 1.6 and we can add this documentation in master also. Should I raise separate pull request for master?

**Comment by velvia** [comment]
Sure, thanks.   Though we should be merging the spark-2.0-preview branch at some point.

**Comment by vatsalmevada** [comment]
@velvia I have created another pull request for master #833.

**Comment by velvia** [comment]
Thanks again Vatsal!

**Pull request merged**
