### PR TITLE
Upgrade spark to 2.1.

### PR DESCRIPTION
**Pull request by aa8y**
Also,
- Fix existing compile errors.
- Sort variables in `Versions.scala` for readability.
- Update shapeless to latest version.
- Make `Versions.scala` the one-stop for all version resolution rather than re-resolving them in `Dependencies.scala`.

### CODE REVIEW

**Comment by noorul** [comment]
@aa8y One of the test is failing

**Comment by aa8y** [comment]
@noorul I can't figure out how to get the python tests to pass locally to fix whatever the problem is. I tried installing `pyspark` from the Spark binary but there is no `setup.py` for 1.6.2.

**Comment by aa8y** [comment]
The above comment was intended for my other PR. Anyway, which test are you referring to? The `HiveJobSpec` and `JavaHiveSpec` compilation errors or the `JobCassandraDAOSpec` one. The latter passed for me locally and I am looking into the former. Also, I am assuming we're ignoring the Python tests for now since they have been failing consistently for all Spark 2.x builds on Travis.

**Comment by noorul** [comment]
I am referring to JobCassandraDAOSpec one

**Comment by noorul** [comment]
@aa8y Also did you see https://github.com/spark-jobserver/spark-jobserver/pull/762 ?

**Comment by noorul** [comment]
@velvia @hntd187 Are we planning to go with 2.1 for 0.8.0 ?

**Comment by velvia** [comment]
At this point probably. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
"We can do no great things, just small things with great love." -mother Teresa

**Comment by aa8y** [comment]
@noorl I did not see that existing PR before. Anyway, I think the problem is because of how `TestHiveContext` is build differently in Spark 2.x vs 1.6. I think this would be an easier problem to fix if we bring `SparkSession` into the picture in SJS.

**Comment by aa8y** [comment]
Also, @noorul is there a way to retrigger Travis so that we can make sure the `JobCassandraDAOSpec` test is actually failing. Because it seems to pass locally for me.

**Comment by noorul** [comment]
@aa8y You could close the PR and re-open. This would trigger the travis build again. I agree that we should be using SparkSession. But we could merge this once the tests pass.

**Comment by aa8y** [comment]
@noorul The `JobCassandraDAOSpec` has passed even though the Python ones failed (as expected). I think this means it should be ready for merge. Feel free to look at the changes I made. I amended the commit.

**Comment by noorul** [comment]
@aa8y There are still compilation errors 

https://travis-ci.org/spark-jobserver/spark-jobserver/builds/215175534#L5915

**Comment by noorul** [comment]
See line 5915 in https://travis-ci.org/spark-jobserver/spark-jobserver/builds/215175534#L5915

**Comment by aa8y** [comment]
@noorul I am aware of those. I mentioned them before in my comments. It doesn't seem like there is an easy fix for them. And they should be preexisting errors. So I would like to address them in a different commit. I think specific and smaller commits are easier to review anyway.

**Comment by noorul** [comment]
@aa8y Merged! Thank you!

**Pull request merged**
