### PR TITLE
Always respond with correct JSON

### PR DESCRIPTION
**Pull request by xjrk58**
Spark job server should always respond with correct json if the mime type is application/json

### CODE REVIEW

**Comment by noorul** [comment]
This might break compatibility. Better to document this change.

**Comment by noorul** [comment]
Can you rebase?

**Comment by velvia** [comment]
@xjrk58 do you want to rebase with master / merge in latest changes?

**Comment by velvia** [comment]
@xjrk58 I restarted Travis.  Seems to be broken due to some error running ScalaStyle.....   also did the merge merge cleanly?  I clicked on the overall changes and saw some merge conflicts....  anyways thanks for merging master.   I don't see git pushes, only PR comments, so didn't know this was updated.

**Comment by velvia** [comment]
@xjrk58 thanks, I think the new PR by @roarking covers this.

**Pull request closed without merging**
