### PR TITLE
Jobserver 0.6.0 spark 1.4.1

### PR DESCRIPTION
**Pull request by JohnsonWang1**

### CODE REVIEW

**Comment by velvia** [comment]
Sorry, don't understand this.  Did you mean to back port master changes to the spark 1.4.1 branch?

**Comment by velvia** [comment]
@noorul do u understand what this is about?

**Comment by velvia** [comment]
@JohnsonWang1 @noorul I'm going to close this PR unless I hear from you guys, as it seems this is a mistake ...  from the comments/titles of commits these are commits/fixes from master which you mean to merge to the spark-1.4.1 branch, right?

**Comment by noorul** [comment]
@velvia Looks like a mistake.

**Pull request closed without merging**
