### PR TITLE
Upgrade Slick to 3.1.1

### PR DESCRIPTION
**Pull request by hntd187**
This upgrades slick to the current latest version, I may be composing this wrong or I may have some style or formatting issues, so please feel free to nit pick a lot on that.

### CODE REVIEW

**Comment by noorul** [comment]
There are random failures in travis.

**Comment by hntd187** [comment]
I am going to look into fixing these flaky tests because this is driving me nuts with these random tests failing.

**Comment by velvia** [comment]
Thanks, much appreciated.

**Comment by zeitos** [comment]
@hntd187 were you able to take a look at it?

**Comment by hntd187** [comment]
@zeitos I have and I'm pretty sure I know what is causing the stuff, I believe it's because the projects are being built concurrently and as a result the jars aren't where they are supposed to be causing the jar upload test to fail. The timeout tests I'm a bit less sure what is going on there. I've read the code  involved in it and there is nothing that seems obviously going on in it, but I  want to reduce the concurrency in that portion of the testing to see if it's more consistent because it's not that it never passes it's just not consistent which seems to be a concurrency issue to me.

**Comment by velvia** [comment]
Hey you guys you might want to take a look at my PR

https://github.com/spark-jobserver/spark-jobserver/pull/442

I removed one of the failing tests

https://github.com/spark-jobserver/spark-jobserver/pull/442/commits/86af04c2aeb43a50758a0cbb39bd4c0c8cd38e32

I’d love to have other feedback on the PR.

**Comment by hntd187** [comment]
@velvia I think your fixes to the tests should take care of the flakey-ness, let's get the new job API in and then I can rebase off that and resubmit, sound good?

**Comment by velvia** [comment]
Sounds awesome.  Well now you can merge those changes  :)

**Comment by hntd187** [comment]
We're mostly up to date now on dependencies

Scala 2.10.6
```
[info] Set current project to root (in build file:/home/scarman/projects/spark-jobserver/)
[info] Found 3 dependency updates for akka-app
[info]   io.netty:netty-all           : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time          : 2.9.3        -> 2.9.4                      
[info]   org.scala-lang:scala-library : 2.10.6                       -> 2.11.8     
[info] Found 3 dependency updates for job-server-tests
[info]   io.netty:netty-all           : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time          : 2.9.3        -> 2.9.4                      
[info]   org.scala-lang:scala-library : 2.10.6                       -> 2.11.8     
[info] Found 3 dependency updates for root
[info]   io.netty:netty-all           : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time          : 2.9.3        -> 2.9.4                      
[info]   org.scala-lang:scala-library : 2.10.6                       -> 2.11.8     
[info] Found 3 dependency updates for job-server-api
[info]   io.netty:netty-all           : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time          : 2.9.3        -> 2.9.4                      
[info]   org.scala-lang:scala-library : 2.10.6                       -> 2.11.8     
[info] Found 3 dependency updates for job-server-extras
[info]   io.netty:netty-all           : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time          : 2.9.3        -> 2.9.4                      
[info]   org.scala-lang:scala-library : 2.10.6                       -> 2.11.8     
[info] Found 6 dependency updates for job-server
[info]   com.h2database:h2            : 1.3.176                      -> 1.4.192             
[info]   io.netty:netty-all           : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final         
[info]   joda-time:joda-time          : 2.9.3        -> 2.9.4                               
[info]   org.apache.shiro:shiro-core  : 1.2.4        -> 1.2.5                               
[info]   org.flywaydb:flyway-core     : 3.2.1                                       -> 4.0.3
[info]   org.scala-lang:scala-library : 2.10.6                       -> 2.11.8              
[success] Total time: 3 s, completed Jun 20, 2016 10:53:56 AM
```

And Scala 2.11.8
```
[info] Set current project to root (in build file:/home/scarman/projects/spark-jobserver/)
[info] Setting version to 2.11.8
[info] Reapplying settings...
[info] Set current project to root (in build file:/home/scarman/projects/spark-jobserver/)
[info] Found 2 dependency updates for job-server-tests
[info]   io.netty:netty-all  : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time : 2.9.3        -> 2.9.4                      
[info] Found 2 dependency updates for job-server-api
[info]   io.netty:netty-all  : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time : 2.9.3        -> 2.9.4                      
[info] Found 2 dependency updates for job-server-extras
[info]   io.netty:netty-all  : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time : 2.9.3        -> 2.9.4                      
[info] Found 6 dependency updates for job-server
[info]   com.h2database:h2                   : 1.3.176                      -> 1.4.192             
[info]   com.typesafe.akka:akka-testkit:test : 2.3.15                       -> 2.4.7               
[info]   io.netty:netty-all                  : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final         
[info]   joda-time:joda-time                 : 2.9.3        -> 2.9.4                               
[info]   org.apache.shiro:shiro-core         : 1.2.4        -> 1.2.5                               
[info]   org.flywaydb:flyway-core            : 3.2.1                                       -> 4.0.3
[info] Found 5 dependency updates for akka-app
[info]   com.typesafe.akka:akka-cluster        : 2.3.15                       -> 2.4.7      
[info]   com.typesafe.akka:akka-slf4j:provided : 2.3.15                       -> 2.4.7      
[info]   com.typesafe.akka:akka-testkit:test   : 2.3.15                       -> 2.4.7      
[info]   io.netty:netty-all                    : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time                   : 2.9.3        -> 2.9.4                      
[info] Found 2 dependency updates for root
[info]   io.netty:netty-all  : 4.0.29.Final -> 4.0.37.Final -> 4.1.1.Final
[info]   joda-time:joda-time : 2.9.3        -> 2.9.4                      
[success] Total time: 3 s, completed Jun 20, 2016 10:55:51 AM
```

The other major versions aside from akka and netty should be pretty easy to upgrade. The final major upgrade from this fro me is to upgrade to the latest version of drop wizard so we can get ride of yammer metrics.

**Comment by hntd187** [comment]
If there are no objects, I'll merge this

**Comment by zeitos** [comment]
I have a question... but I guess it's too late ... 
I'm joking 👍

**Pull request merged**
