### PR TITLE
fix(root): build.sbt for job-server-extras project does not include publishing assembly #828

### PR DESCRIPTION
**Pull request by zromi18**
Issues:
- The build.sbt for job-server-extras project does not include publishing assembly

Fixes:
- Added publishing settings for assembly in job-server-extras proejct

Pull Request checklist:
- [X] The commit(s) message(s) follows the contribution guidelines ?
- [No] Tests for the changes have been added (for bug fixes / features) ?
- [No] Docs have been added / updated (for bug fixes / features) ?

Current behavior :
- The publish task has no effect on job-server-extras assembly

New behavior :
- The assembly from job-server-extras can be published

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/855)

### CODE REVIEW

**Comment by zromi18** [comment]
I am using separate projects for building docker images. They are based on different Linux flavors (Ununtu, CentOS and Alpine) and different JDKs, JREs, but all of them are relying on Spark JobServer assembly jar. So I publish assembly jar to my Nexus (ivy) central repository and docker build projects take assembly jar from there.

**Comment by velvia** [comment]
@noorul @zeitos @hntd187 any thoughts on this one?   I don't think enabling assembly publishing is the way to go.

**Comment by noorul** [comment]
@velvia I agree. Especially when compiling gives the flexibility to tweak certain things. Like the Spark minor versions.

**Comment by velvia** [comment]
@zromi18 I'm going to close this one as I don't think we want to move ahead with automatically enabling publishing an assembly.  I'm open to an approach where we enable publishing the assembly with an environment var for example, but some setting that is not default.

**Pull request closed without merging**
