### PR TITLE
Changed frontend application

### PR DESCRIPTION
**Pull request by andreaferretti**
Hello, I have taken the liberty to develop a single page application that exposes all the API available in the Spark JobServer. It can be used as a drop-in replacement for the current jQuery app, but also covers creating and deleting contexts, launching jobs, checking the results and uploading jars.

The source can be found under

https://github.com/unicredit/spark-jobserver-frontend

Here I have put the compiled version. Check if you think it can be good for you, and let me know if you think I should make any improvement.

If you are interested in how it was developed, I used Facebook React and CoffeeScript, with Bootstrap for the CSS and a few other libraries.

### CODE REVIEW

**Comment by velvia** [comment]
Sorry guys, really need to look into this and check out the UI.

**Comment by jeffsteinmetz** [comment]
I've been using this new front end for some time now.  been working well so far.  What if the front end code was it's own repo?

**Comment by andreaferretti** [comment]
It already is, and I would be happy if the authors would fork it. The only issue I see is that one has to:

* either package the frontend inside the jobserver
* or allow CORS for requests to the jobserver API

Both solutions require to fiddle with the jobserver - as opposed to just building it from source - and thus may be inconvenient for newcomers

**Comment by jeffsteinmetz** [comment]
The front end repo could include a script that distributes the resulting
html and JS to the appropriate directory in the job server build.

**Comment by andreaferretti** [comment]
I think this could work if the frontend was a git submodule. Otherwise I am not sure how the frontend could even locate the jobserver directory

**Comment by velvia** [comment]
So let me summarize what's going on here:
* We don't need this PR because the repo is already elsewhere
* We could fork the frontend repo..... I can take this as an AI to fork it within spark-jobserver account for convenience  (only problem is then it has to be kept up to date)
* We want CORS support in jobserver itself..... @jeffsteinmetz want to submit a PR?
* Packaging the frontend so that jobserver could use it.... could this be done via http://www.webjars.org/ ?

**Comment by jeffsteinmetz** [comment]
The web front end from andreaferretti is also 100% html/javascript.
If the static html/javascript was served from the jobserver (as it is now), then CORS isn't required.
I've tested it and it works well.

The option andreaferretti is proposing would be to start iterating on the UI within the jobserver itself, adopting his code 100% and making it a first class citizen within the repo.  I.e, what this PR is for.

If the UI was a separate Repo, (after a brief glance) it does look like it could use a web jar to resolve the html/javascript dependencies so that the jobserver can host the content without CORS required.

If it was a completely separate project, with its own web server (node.js or similar), then yes it would need CORS.

**Comment by jeffsteinmetz** [comment]
actually - one clarification.  I was not entirely correct when I stated what this PR is for.
This PR does "not" include the scripts that build the resulting minified CSS, JS, etc., so yes it would need to be its own repo.

This PR can probably be closed since there would be no way to maintain the front end code without the gulp build scripts, etc.

Forking his UI may be best, and then have the fork build the web jar to include the UI.
A new PR would be to include the web jar.

I admit I am not a gulp, browserify, watchify expert so not sure what the best integration approach is to build said web jar.

**Comment by velvia** [comment]
Jeff, if you're willing to take on this work, to fork and integrate the UI,
let me know, I'd be happy to support you.

On Thu, Jan 22, 2015 at 10:35 AM, Jeff Steinmetz <notifications@github.com>
wrote:

> actually - one clarification. I was not entirely correct when I stated
> what this PR is for.
> This PR does "not" include the scripts that build the resulting minified
> CSS, JS, etc., so yes it would need to be its own repo.
>
> This PR can probably be closed since there would be no way to maintain the
> front end code without the gulp build scripts, etc.
>
> Forking his UI may be best, and then have the fork build the web jar to
> include the UI.
> A new PR would be to include the web jar.
>
> I admit I am not a gulp, browserify, watchify expert so not sure what the
> best integration approach is to build said web jar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/pull/26#issuecomment-71072783>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by jeffsteinmetz** [comment]
Has anybody found an example of how to build a web jar using a really simple SBT build script?

The web jar site has maven examples - I've never built anything with maven (nor do I have time right now to learn another build tool that I won't likely use again).

I primarily stick to straight forward, simple, sbt builds at this point.

**Comment by jeffsteinmetz** [comment]
What about referencing the web UI from the spark-job server directly in SBT via git (no webjars)?

object Projects {
  lazy val depProject = RootProject(uri("git://github.com/spark-jobserver/spark-jobserver-ui.git#%s".format(V.depProject)))
}

**Comment by velvia** [comment]
Hm, I suppose that's possible.  Should we go ahead and just fork the UI
project?

On Fri, Feb 6, 2015 at 9:11 AM, Jeff Steinmetz <notifications@github.com>
wrote:

> What about referencing the web UI from the spark-job server directly in
> SBT via git (no webjars)?
>
> object Projects {
> lazy val depProject = RootProject(uri("git://
> github.com/spark-jobserver/spark-jobserver-ui.git#%s
> ".format(V.depProject)))
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/pull/26#issuecomment-73274198>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by jeffsteinmetz** [comment]
Yes – as long as SBT can kick off the gulp build as well.  I see there is 
a gulp plugin for sbt.
GULP builds the HTML / minified files from his coffee script.

From:  Evan Chan <notifications@github.com>
Reply-To:  spark-jobserver/spark-jobserver 
<reply+0053bdbb71e8af10a62dfc82015f938cd92b4f3e049e149c92cf0000000110ecd06c
92a169ce030a21a9@reply.github.com>
Date:  Friday, February 6, 2015 at 10:56 AM
To:  spark-jobserver/spark-jobserver <spark-jobserver@noreply.github.com>
Cc:  Jeff Steinmetz <jeffrey.steinmetz@gmail.com>
Subject:  Re: [spark-jobserver] Changed frontend application (#26)

Hm, I suppose that's possible.  Should we go ahead and just fork the UI
project?

On Fri, Feb 6, 2015 at 9:11 AM, Jeff Steinmetz <notifications@github.com>
wrote:

> What about referencing the web UI from the spark-job server directly in
> SBT via git (no webjars)?
>
> object Projects {
> lazy val depProject = RootProject(uri("git://
> github.com/spark-jobserver/spark-jobserver-ui.git#%s
> ".format(V.depProject)))
> }
>
> —
> Reply to this email directly or view it on GitHub
> 
><https://github.com/spark-jobserver/spark-jobserver/pull/26#issuecomment-7
>3274198>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by andreaferretti** [comment]
I used gulp as it is a pretty standard tool in the JS community. I think the simplest thing for you would be to fork the UI (of course I would be happy to help if there is need to add features or fix bugs) and build it with gulp manually. Of course, if there is an SBT plugin for that, even better, but it requires gulp installed anyway, so it just a small convenience to avoid having to make the build separately. Note that gulp allows you to develop live with the command `gulp watch`, so I guess that while developing the UI it is simpler to work with gulp directly

**Comment by velvia** [comment]
@andreaferretti  @jeffsteinmetz  I just invited you guys to collaborate on a fork of the spark-jobserver-frontend repo in github.com/spark-jobserver.   Hope this can get things going!   LMK if we should jump on a call or something to move this forward.

**Comment by andreaferretti** [comment]
Sure, let me know what you think is missing!

**Comment by jeffsteinmetz** [comment]
Great first step.  
Cheers


From:  Evan Chan <notifications@github.com>
Reply-To:  spark-jobserver/spark-jobserver 
<reply+0053bdbbf200e0da6495b8330ddd9981339622ee5a288b0792cf0000000110fd02fb
92a169ce030a21a9@reply.github.com>
Date:  Wednesday, February 18, 2015 at 5:48 PM
To:  spark-jobserver/spark-jobserver <spark-jobserver@noreply.github.com>
Cc:  Jeff Steinmetz <jeffrey.steinmetz@gmail.com>
Subject:  Re: [spark-jobserver] Changed frontend application (#26)


@andreaferretti  @jeffsteinmetz  I just invited you guys to collaborate on 
a fork of the spark-jobserver-frontend repo in github.com/spark-jobserver. 
  Hope this can get things going!   LMK if we should jump on a call or 
something to move this forward.

**Comment by jeffsteinmetz** [comment]
we can probably close this PR, since the alternative front end app now has its own repo.

**Comment by velvia** [comment]
How is that going btw?

On Thu, May 14, 2015 at 2:24 PM, Jeff Steinmetz <notifications@github.com>
wrote:

> we can probably close this PR, since the alternative front end app now has
> its own repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/pull/26#issuecomment-102175207>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by addisonj** [comment]
FYI, I have been using this frontend in my local SJS for the last 3 weeks. There is only one major bug which is that I don't think JAR uploading works and I think there may be some weirdness around retrieving status from jobs. All told however, it is a huge improvement over current SJS UI and think it woudl be great to get those few things fixed and have this officially merged as the default UI

**Comment by velvia** [comment]
@addisonj @jeffsteinmetz thanks.  Would either of you be willing to walk me or others through what is needed to merge it?

**Comment by jeffsteinmetz** [comment]
The front end "source" would need its own directory.  Then - the spark job server build would need to call gulp file to "build" the html and javascript source.  The gulp file probably needs a small tweak so that it places the final html, css and javascript files in the correct location for the job server to find them (i.e. where it currently expects to find them.).   There are a few SBT gulp runner plugins that I have seen, but never had a chance to use them.  https://github.com/hedefalk/sbt-gulp-task  https://github.com/timcowlishaw/sbt-gulp  etc..

**Comment by zeitos** [comment]
guys... should I close this one since we have https://github.com/spark-jobserver/spark-jobserver-frontend ?

**Comment by velvia** [comment]
Yeah we should close it.  However the idea was to incorporate the front end changes back into the main repo, but I have no idea how to do that.

**Pull request closed without merging**
