### PR TITLE
Feature/jobs delete

### PR DESCRIPTION
**Pull request by f1yegor**
Support for delete jobs

### CODE REVIEW

**Comment by noorul** [comment]
@f1yegor Tests are failing

**Comment by f1yegor** [comment]
Trying to figure out why tests are flaky. It's fine on mine https://travis-ci.org/f1yegor/spark-jobserver/

**Comment by noorul** [comment]
@f1yegor Can you squash commits into one ?

**Comment by f1yegor** [comment]
Messed up squash. see PR #623

**Pull request closed without merging**
