### PR TITLE
Fix manager_start not found during docker deployment

### LINKED ISSUE #477: Docker Deployment - manager_start not found
Cannot run program \"./manager_start.sh\": error=2, No such file or directory

SJS version 0.6.2

curl -d "input.string = a b c a b see" '****:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample'
{
"status": "ERROR",
"result":
{ "errorClass": "java.lang.RuntimeException", "cause": "Cannot run program \"./manager_start.sh\": error=2, No such file or directory", "stack": ["java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)", "scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$1.apply$mcV$sp(AkkaClusterSupervisorActor.scala:222)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$1.apply(AkkaClusterSupervisorActor.scala:221)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$1.apply(AkkaClusterSupervisorActor.scala:221)", "scala.util.Try$.apply(Try.scala:192)", "spark.jobserver.AkkaClusterSupervisorActor.spark$jobserver$AkkaClusterSupervisorActor$$startContext(AkkaClusterSupervisorActor.scala:221)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$wrappedReceive$1.applyOrElse(AkkaClusterSupervisorActor.scala:136)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:467)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"], "causingClass": "java.io.IOException", "message": "java.io.IOException: Cannot run program \"./manager_start.sh\": error=2, No such file or directory" }
}

### PR DESCRIPTION
**Pull request by stannie42**
Fixes #477

### CODE REVIEW

**Comment by noorul** [comment]
Thank you @stannie42

**Comment by stannie42** [comment]
Thank you @noorul Nice to see you again since openstack/solum! :)

**Comment by stannie42** [comment]
@noorul I would like to see this change also in the branch jobserver-0.6.2-spark-1.6.1, should I do a separate PR our can someone cherry-pick this commit ?

**Comment by noorul** [comment]
I think I am going to revert this commit as this is specific to docker

**Comment by noorul** [comment]
@stannie42 Nice to see you too. Small world!

**Comment by noorul** [comment]
I reverted the commit as that fix is specific to docker. This would break non docker deployments.

**Pull request merged**
