### PR TITLE
Make ec2_deploy.sh work with current spark-ec2

### PR DESCRIPTION
**Pull request by mcnels1**
- Fix a broken mkdir by adding -p option
- Get spark-ec2 from its new location as a separate project
- Add additional configuration

### CODE REVIEW

**Comment by mcnels1** [comment]
I'm not familiar with with your CI process, but I don't see how what I changed (ec2_deploy.sh and user-ec2-settings.sh.template) could have caused your tests to fail.

**Comment by velvia** [comment]
@mcnels1 thanks, this looks fine to me.   I'll restart Travis.

**Comment by mcnels1** [comment]
Any suggestions on what to do about the failing CI checks?

**Comment by velvia** [comment]
Hmm, I would ignore it since your change clearly doesn’t change code.   Thought I restarted it, but could be wrong

**Comment by mcnels1** [comment]
I have another pull request ready to submit that builds on this one to support deployment into an EC2 VPC.  I can submit it now or wait until after this one gets merged.  Preferences?

**Comment by noorul** [comment]
@mcnels1 Thank you!

**Pull request merged**
