### PR TITLE
fix: AdHocContext create failure

### PR DESCRIPTION
**Pull request by fuqiliang**
**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** [#1074](https://github.com/spark-jobserver/spark-jobserver/issues/1074)

**New behavior :**
  No ERROR

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1124)

### CODE REVIEW

**Comment by bsikander** [comment]
Please change your commit message according to the [contribution guidelines](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/contribution-guidelines.md).

**Comment by bsikander** [comment]
Ping @fuqiliang

**Comment by velvia** [comment]
I'm fine with this change other than what @bsikander brought up.

**Comment by bsikander** [comment]
@fuqiliang could you please have a look at this?

**Pull request closed without merging**
