### PR TITLE
Add EMR Deploy instruction

### PR DESCRIPTION
**Pull request by apivovarov**
The following instruction explains how to run spark-jobserver on EMR cluster (Spark on YARN).

### CODE REVIEW

**Comment by velvia** [comment]
@apivovarov thanks, this looks good for the most part.  I wish the scripts, the EC2 scripts, and the built in deploy and run scripts could share more content, it is a bit all over the place right now.

**Comment by velvia** [comment]
@zeitos want to look over this?

**Comment by apivovarov** [comment]
@velvia This is not for EC2 and this is not scripts.
I just wanted to explain people how to add jobserver to their EMR cluster.
For now I do not have a goal to create a script for that. Just the instruction.
I look at my company DevOpses and see that they prefer to control the process and they want to have step-by-step instruction on how to add jobserver to EMR.

As for the script. Amazon will include SJS to EMR sooner or later. So, let them focus on the script.

**Comment by zeitos** [comment]
I'll try to test it this week!

**Comment by velvia** [comment]
@zeitos feel free to merge after you've had a chance to try it out

**Comment by zeitos** [comment]
I just verified it and it all looks good and works great!

Thanks!, merging

**Pull request merged**
