### PR TITLE
Bugfix: Custom YARN_CONF_DIR remain unused

### PR DESCRIPTION
**Pull request by MeiSign**
If you change the YARN_CONF_DIR in your env.sh files the parameter was not used by the spark-submit shell because the server_start.sh did not export the parameters.

Effect: The YARN_CONF_DIR of the settings.sh has no effect. The jobserver will always try to connect to localhost(default) in yarn client mode.

### CODE REVIEW

**Comment by velvia** [comment]
Huh, not able to get the Travis CI build to pass  :/

On Mon, Aug 24, 2015 at 7:38 AM, Stefan Meiwald <notifications@github.com>
wrote:

> If you change the YARN_CONF_DIR in your env.sh files the parameter was not
> used by the spark-submit shell because the server_start.sh did not export
> the parameters.
>
> Effect: The YARN_CONF_DIR of the settings.sh has no effect. The jobserver
> will always try to connect to localhost(default) in yarn client mode.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/spark-jobserver/spark-jobserver/pull/221
> Commit Summary
>
>    - Update local.sh.template
>    - These Variables need to be exported
>
> File Changes
>
>    - *M* bin/server_start.sh
>    <https://github.com/spark-jobserver/spark-jobserver/pull/221/files#diff-0>
>    (4)
>    - *M* job-server/config/local.sh.template
>    <https://github.com/spark-jobserver/spark-jobserver/pull/221/files#diff-1>
>    (1)
>
> Patch Links:
>
>    - https://github.com/spark-jobserver/spark-jobserver/pull/221.patch
>    - https://github.com/spark-jobserver/spark-jobserver/pull/221.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/pull/221>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by MeiSign** [comment]
Thats odd... Can't imagine how the changed scripts can throw a sbt resolve error. :-/

----- Ursprüngliche Nachricht -----
Von: "Evan Chan" <notifications@github.com>
Gesendet: ‎25.‎08.‎2015 00:27
An: "spark-jobserver/spark-jobserver" <spark-jobserver@noreply.github.com>
Cc: "Stefan Meiwald" <stefanmeiwald@yahoo.de>
Betreff: Re: [spark-jobserver] Bugfix: Custom YARN_CONF_DIR remain unused(#221)

Huh, not able to get the Travis CI build to pass :/

On Mon, Aug 24, 2015 at 7:38 AM, Stefan Meiwald <notifications@github.com>
wrote:

> If you change the YARN_CONF_DIR in your env.sh files the parameter was not
> used by the spark-submit shell because the server_start.sh did not export
> the parameters.
>
> Effect: The YARN_CONF_DIR of the settings.sh has no effect. The jobserver
> will always try to connect to localhost(default) in yarn client mode.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/spark-jobserver/spark-jobserver/pull/221
> Commit Summary
>
> - Update local.sh.template
> - These Variables need to be exported
>
> File Changes
>
> - *M* bin/server_start.sh
> <https://github.com/spark-jobserver/spark-jobserver/pull/221/files#diff-0>
> (4)
> - *M* job-server/config/local.sh.template
> <https://github.com/spark-jobserver/spark-jobserver/pull/221/files#diff-1>
> (1)
>
> Patch Links:
>
> - https://github.com/spark-jobserver/spark-jobserver/pull/221.patch
> - https://github.com/spark-jobserver/spark-jobserver/pull/221.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/pull/221>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
--- Toni Morrison

**Comment by velvia** [comment]
I'm just gonna merge it.  No way this could cause a build breakage...

**Comment by MeiSign** [comment]
Hopefully not. :> Thx for merging...

**Pull request merged**
