### PR TITLE
Jobserver 0.6.0 spark 1.4.1

### PR DESCRIPTION
**Pull request by jbmahadevan**

### CODE REVIEW

**Comment by noorul** [comment]
Not sure why are you trying to merge code into master from jobserver-0.6.0-spark-1.4.1?

**Comment by jbmahadevan** [comment]
| 
Hi It is by mistake I clicked the link. I need to clone the repository in my local environment.
How to release this?

Sent from Yahoo7 Mail on Android 
|  From:"Noorul Islam K M" <notifications@github.com>
Date:Fri, 30 Oct, 2015 at 12:40 pm
Subject:Re: [spark-jobserver] Jobserver 0.6.0 spark 1.4.1 (#298)



 Not sure why are you trying to merge code into master from jobserver-0.6.0-spark-1.4.1?—
Reply to this email directly or view it on GitHub.   |

 |

**Comment by velvia** [comment]
Hi, what are you trying to accomplish?  By release do you mean cut a local jar for your local maven server?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by jbmahadevan** [comment]
This was done by mistake i am closing this pull request. I though pull request would give a link so that i can download the git repo :(

**Comment by jbmahadevan** [comment]
HI, I am not going to update anything or commit on something. It is checked out by mistake.I closed it. Regards 
Mahadevan JB 
9916534065 (Bangalore) 


     On Friday, October 30, 2015 2:18 PM, Evan Chan <notifications@github.com> wrote:
   

 Hi, what are you trying to accomplish? By release do you mean cut a local jar for your local maven server?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by jbmahadevan** [comment]
Hi Spark team, I would need help on resolving the below issue. 
   curl --data-binary /opt/hadoop/spark-jobserver/job-server-tests/target/scala-2.10/job-server-tests-0.6.1-SNAPSHOT.jar localhost:8090/jars/test{  "status": "ERROR",  "result": "Jar is not of the right format"
I just build the jar in the RHEL environment. I executed the unzip of the job-server-tests-0.6.1-SNAPSHOT.jar it is expanding properly.
Could you please help me out here?
Regards 
Mahadevan JB 
9916534065 (Bangalore)

**Comment by velvia** [comment]
Try putting @ before the path - e.g. —data-binary @/opt/hadoop/….

Without this curl thinks the path is the data being sent.

**Pull request closed without merging**
