### PR TITLE
misc(github): add issue template

### PR DESCRIPTION
**Pull request by derSascha**
In most of the issues, the first question is ,,what spark and jobserver version are you using?''. Hopefully this template eliminates this questions.

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/935)

### CODE REVIEW

**Comment by noorul** [comment]
I thought of doing this. Thank you for the initiative.

**Comment by noorul** [comment]
We need more questions to be asked.

1. Which version of Spark
2. Is it deployed as Stadalone Cluster, Yarn, Meos?
3. What is SJS version?
4. Reproducible recipe?
5. Logs

**Comment by derSascha** [comment]
@noorul new version with some more details. Anything missing?

**Comment by noorul** [comment]
Merged!  Thank you !

**Pull request merged**
