### PR TITLE
misc(jobserver): Used correct spark download URL

### PR DESCRIPTION
**Pull request by noorul**
**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1171)

### CODE REVIEW

**Comment by bsikander** [comment]
This url looks stable. Should I just merge this change?

**Comment by noorul** [comment]
Tests are failing.

**Comment by bsikander** [comment]
Retriggered the tests. Unrelated tests failed.

**Comment by noorul** [comment]
@bsikander You can re-trigger from Travis

**Pull request merged**
