### PR TITLE
Keep original extension on uploaded file if provided

### LINKED ISSUE #963: Why change the file type of uploaded data to .dat?
Currently, files upload to `/data` is renamed as filename-datetime.dat.   
Is this the correct design? Who will use .dat as a resource?

### PR DESCRIPTION
**Pull request by rfrohock**
**Pull Request checklist**

- [x ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?  
There are no existing tests to update for data uploads
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior: ** 
Resolves #963,  Sets the extension of the uploaded data file to match what was provided in the upload.  Previously all uploaded data files where changes to have an extension of ".dat"

**New behavior: **
When the data file is uploaded, if there is an extension, the extension is "moved" to after the time-stamp indicating when the data file was uploaded.  

**Other information**:
We needed to add this when using secondary EGG files,  Python would not recognize the ".dat" file as a valid source for Python Class definition even if that file reference was added using pyFiles() call.

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/991)

### CODE REVIEW

**Comment by bsikander** [comment]
@noorul I am not sure about the impact of this change. What is your opinion on this?

**Comment by velvia** [comment]
@noorul is probably the best person for this, or someone else more familiar with the Python stuff.

**Comment by bsikander** [comment]
@noorul can this PR be merged?

**Comment by valan4ik** [comment]
Closing due to inactivity.

**Pull request closed without merging**
