### PR TITLE
Add DSE Spark Master Provider

### PR DESCRIPTION
**Pull request by noorul**

### CODE REVIEW

**Comment by noorul** [comment]
@RussellSpitzer Can you please review this and provide feedback? Or do you have something similar @DataStax ?

**Comment by velvia** [comment]
Noorul, I think you would not need this if you were using DSE no?  Or is this for an older version of DSE?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by noorul** [comment]
We need this. When DSE elects new master and we need to restart spark jobserver then it will pick the hardcoded master from local.conf.

**Comment by velvia** [comment]
What I mean is that DSE 4.8 already includes the job server, and would surely have something like this.... including it could conflict with future versions / changes ...

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by RussellSpitzer** [comment]
No we don't include the "master provider" yet :) It got pushed back

**Comment by noorul** [comment]
We are not using sjs that is coming with dse 4.8.0. Also as Russel said they did not implement this. Can this be merged?

**Comment by velvia** [comment]
Sure.  Lemme have a closer look later.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
@noorul left you some minor comments, mostly style, but I think would help make code more compact and easier to read.

Now here's the thing - I think overall this is valuable, but the SparkMasterProvider is meant to be a pluggable interface, and not everyone uses DSE.   I think a better place for this is as a separate module, or separate repo, and those that want to include it can then include it, without the need to increase the dependencies of core.  What do you think?   

That could be a spark-jobserver-cassandra module, with not only your provider, but other goodies: a Cassandra DAO, and perhaps a CassandraContext for parsing C* tables.

**Comment by noorul** [comment]
I agree that the code should belong somewhere else. Initially I though of
debating this in the mailing list before raising PR, then I thought any how
you comment on that in the PR.

**Comment by noorul** [comment]
@velvia Shall I create repo named spark-jobserver-cassandra? If so, is there any project template to get the basic structure up?

**Comment by velvia** [comment]
@noorul hmmm.  Yeah we can create that repo.  However for project template...     how about this, let me create that repo, and set up the basic structure.   I have an idea to use it for other things, like to create a cassandra DAO and cassandra specific query jobs.  In the meantime, do you want to address my other CR comments first, and push changes to this PR?

**Comment by noorul** [comment]
Sure! Thanks!

**Comment by noorul** [comment]
We are looking to go live with code from this repository. It will be great we could merge this soon.

**Comment by velvia** [comment]
@noorul I'm going to go ahead and create the other repo now.

**Comment by velvia** [comment]
@noorul repo added, go ahead and put your code their.  Added build files, including ability to build assembly.  Should be good to go.  Can then close this once code is moved over?

**Comment by velvia** [comment]
Going to close this, since we have the other repo for this now.

**Pull request closed without merging**
