### PR TITLE
Added CORS Support and EC2 Support

### PR DESCRIPTION
**Pull request by David-Durst**
This commit mainly adds support for 2 features. First, it enables CORS support
so that requests can be made across domain names. Second, it adds a script
for deploying the job-server to EC2. The commit also includes an example to
run on the EC2 cluster. Finally, there are improvements in the bin/ scripts
to better support paths with spaces in them. Previously, these paths had
caused issues with the bin/sever_deploy.sh script.

### CODE REVIEW

**Comment by velvia** [comment]
@David-Durst thanks!  I'm really looking forward to trying out the K-Means example.   Only took a brief look through it, and will be offline for about 2 days.

**Comment by David-Durst** [comment]
I made the changes. Let me know what you think.

**Comment by David-Durst** [comment]
Unfortunately, I can't fix the spark-ec2 issues as it is part of the Spark distribution.

**Comment by velvia** [comment]
@David-Durst are you saying that the spark EC2 scripts download the distro into the current dir?   Sorry not sure exactly what you're referring to.

Rest of it looks fine to me.   I'd like to try the K-Means example tonight.

**Comment by David-Durst** [comment]
There are two parts. 
- First, for the .gitignore issue, spark-jobserver's bin/ec2_deploy.sh downloads the entire Spark distro. I did this because the [documentation for Spark's spark-ec2 script](http://spark.apache.org/docs/latest/ec2-scripts.html) assumes that the script is run in the ec2 folder inside a complete Spark release. Therefore, separating it from the rest of Spark may lead to undefined behavior. spark-jobserver's bin/ec2_deploy.sh runs Spark's spark-ec2 to deploy to the EC2 cluster. I put the Spark .tgz and the unzipped directory containing Spark in spark-jobserver's .gitignore so that they aren't added to the spark-jobserver repo after the user runs spark-jobserver's bin/ec2_deploy.sh.

- Second, I have found the spark-ec2 script to be unreliable. It sometimes hangs with the error message I describe in 0159d8b. Unfortunately, spark-ec2 is the best option at the moment for spinning up and shutting down a cluster from the command line.  If the spark-ec2 script hangs and causes my my ec2_deploy script to hang, I recommend killing the cluster and restarting the ec2_deploy process. See 0159d8b for complete instructions. It is easy to do and currently the best option.

**Comment by David-Durst** [comment]
I turns out I was wrong on the first point. I have fixed it so that you no longer need to download the entire Spark repo to your local machine.

**Comment by velvia** [comment]
Sweet thanks.  Sorry very busy as I prepare to fly to Amsterdam to talk
about Spark Job Server!   Will look at your PR once I settle down.

On Wed, Oct 21, 2015 at 8:45 PM, David Durst <notifications@github.com>
wrote:

> I turns out I was wrong on the first point. I have fixed it so that you no
> longer need to download the entire Spark repo to your local machine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/pull/290#issuecomment-150098190>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
@David-Durst probably won't get time to try out the K-Means example, but going to merge as this looks good.  Many thanks!

**Pull request merged**
