### PR TITLE
Support Spark 1.5.0 ?

### PR DESCRIPTION
**Pull request by zeitos**

### CODE REVIEW

**Comment by velvia** [comment]
Let’s get 1.4.1 merged first, do a release, then get 1.5.0 on master.   Shouldn’t skip versions I think.

**Comment by zeitos** [comment]
Great, I'm looking into the failing tests right now.

Btw, will this release be 0.5.3 or 0.6?: new spark version support, +shiro, +docker (that alone was a great feature)

**Comment by velvia** [comment]
0.6, because of +shiro +https both are really big features

**Comment by zeitos** [comment]
Closed this one in favor of https://github.com/spark-jobserver/spark-jobserver/pull/256

**Pull request closed without merging**
