### PR TITLE
Upgrade spray to 1.3.3

### PR DESCRIPTION
**Pull request by v-gerasimov**
Upgrade:

* spray-can -> 1.3.3
* spray-routing -> 1.3.3
* spray-client -> 1.3.3

Spary 1.3.3 contains fixes of different bugs and improvements, here is changelog of Spray 1.3.3

Changelog of Spray 1.3.3: https://github.com/spray/spray/blob/v1.3.3/CHANGELOG

### CODE REVIEW

**Comment by velvia** [comment]
What about spray-json? 
Would you mind posting the details, and why we should upgrade, to the PR description?  Thanks!

**Comment by v-gerasimov** [comment]
@velvia spray-json is another project https://github.com/spray/spray-json. It has 1.3.2 version and has been updated now.

Spary 1.3.3 contains fixes of differents bugs and improvements, here is changelog of Spray 1.3.3.

Changelog of Spray 1.3.3: https://github.com/spray/spray/blob/v1.3.3/CHANGELOG

**Comment by velvia** [comment]
Ok.  How about we merge this after releasing 0.6.0?

**Comment by v-gerasimov** [comment]
@velvia Yes, of course. Thanks!

**Comment by velvia** [comment]
@v-gerasimov thanks, going to merge this.

**Pull request merged**
