### PR TITLE
Eclipse

### PR DESCRIPTION
**Pull request by msohn**
Enable using Eclipse for spark-jobserver development

### CODE REVIEW

**Comment by noorul** [comment]
@msohn This might conflict with https://github.com/spark-jobserver/spark-jobserver/pull/561

**Comment by msohn** [comment]
ok, I see
Should I rebase #619 onto #561 ?
Or should #561 rebase onto #619 considering this pull request is a lot less complex ?

**Comment by noorul** [comment]
I would suggest you to try #561 and see whether Eclipse issue is getting fixed.

**Comment by msohn** [comment]
I tried, and there are some non-standard package paths left, see my comment on #561

**Comment by velvia** [comment]
Agreed, I would merge this with #561 and @htnd187’s efforts.

Also I do not think sbt-eclipse plugin belongs in this project. You can stash that in your ~/.sbt/0.13/plugins/plugins.sbt.  Projects should remain independent of IDE.

**Comment by msohn** [comment]
ok, I am fine with putting the sbt-eclipse plugin in my local sbt configuration

How about additions to .gitignore ? Should I ignore them locally in .git/info/exclude or shall this be shared ?

**Comment by velvia** [comment]
Oh do you mean to exclude the IDE files in .gitignore?  I’m fine with that, didn’t know about .git/info/exclude

**Comment by noorul** [comment]
@msohn You can global ignore file

git config --global core.excludesfile '~/.gitignore'

**Comment by msohn** [comment]
I know how git works (I am a committer on JGit) but I am wondering if we should share the additional .gitignore entries required when using Eclipse to hack on the spark-jobserver by adding them to the project's .gitignore or if you prefer that developers using Eclipse ignore those files locally either using .git/info/exclude or the user's global ignore file

**Comment by noorul** [comment]
@msohn I was not aware of the fact that you are a commiter on JGit.

I would prefer IDE specific ignores outside of the project.

**Comment by msohn** [comment]
ok, then I abandon this pull request

**Pull request closed without merging**
