### PR TITLE
fix(ci): add docker publish support

### PR DESCRIPTION
**Pull request by noorul**
**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?

**Current behavior :**

We need to manually publish docker build

**New behavior :**

Publish docker build for every master build

---
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/847)

### CODE REVIEW

**Comment by noorul** [comment]
Work in progress, not ready for review

**Comment by noorul** [comment]
This is work in progress!

**Comment by noorul** [comment]
Is there a way to mark a PR as work in progress?

**Comment by noorul** [comment]
Created a lable wip and applied it

**Comment by velvia** [comment]
I typically also add WIP to the title of the PR or commits.

**Comment by velvia** [comment]
Ok, thanks for wip label.   So when you're done you take off the wip label and then it's ready for review?

**Comment by velvia** [comment]
BTW I don't think `sbt docker` by itself publishes.  There is still a manual step of actually pushing the image to dockerhub.

**Comment by velvia** [comment]
@noorul any progress on this?

**Comment by valan4ik** [comment]
I like the idea, but as PR is 3 years old now and there is no activity, I will close it.

**Pull request closed without merging**
