### PR TITLE
Adding Newsweaver to list of SJS users

### PR DESCRIPTION
**Pull request by PierreVincent**
We have been using the Spark Job Server at Newsweaver for a few months now, so could we add our name to the list of users?

Thanks!
Pierre

### CODE REVIEW

**Comment by noorul** [comment]
Thank you!

**Comment by velvia** [comment]
Thanks Pierre!  Do you guys have a logo that I could possibly use at an upcoming presentation?

**Comment by PierreVincent** [comment]
@velvia, sure you can use this logo:
newsweaver-logo

**Comment by PierreVincent** [comment]
I see you are doing a talk about the Job Server at Spark Summit in Amsterdam! 2 of our developers are attending so they might get to talk to you about how we're getting on with the Job Server! I will be in Amsterdam myself but I'm attending Velocity which starts on the same day :(

**Comment by velvia** [comment]
Pierre,

Thanks!  Yes I’ll be speaking in Amsterdam, and would love to chat with you guys!
Sorry to miss you at conf, but we can always grab drinks/coffee  :)

**Pull request merged**
