### PR TITLE
feat(job-server): pass context name as appName when context is submitted

### PR DESCRIPTION
**Pull request by climber73**
This change is [Reviewable](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1156)

### CODE REVIEW

**Comment by bsikander** [comment]
What is the reason for this change? What issue did you had?

Also for commit messages please follow the [guidelines](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/contribution-guidelines.md).

**Comment by noorul** [comment]
I think this PR helps the spark context to be named as actual name of the context instead of "JobManager"

**Comment by climber73** [comment]
Yes, @noorul is right. We had to launch several contexts with different settings and faced several equal applications named "JobManager" in YARN UI.

**Comment by bsikander** [comment]
Retriggering the build.

**Comment by bsikander** [comment]
LGTM

**Pull request merged**
